title: The X Space
description: Stay foolish, stay hungry
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://yafengxn.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman-blog

# social
author: yafengxn
image: /thumbnail-jumbo.png
twitter:
  username: yafengxn

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
